// gRPC types generated by ts-proto. A separate entry point, because it pulls in
// @nestjs/microservices and @grpc/grpc-js, which clients never load.
export * as identityGrpc from '../generated/wayfare/identity/device.pb';
export * as healthGrpc from '../generated/grpc/health/v1/health.pb';
export * from './proto-enums';
