// gRPC types generated by ts-proto. A separate entry point, because it pulls in
// @nestjs/microservices and @grpc/grpc-js, which clients never load.
export * as identityGrpc from './identity';
export * as healthGrpc from '../generated/grpc/health/v1/health.pb';
export * as commonGrpc from '../generated/wayfare/common/page.pb';
export * as timestampGrpc from '../generated/google/protobuf/timestamp.pb';
export * from './proto-enums';
