/**
 * Audited actions, past tense (rdm-spec I-11 `action`). Every action named on an *Audit action(s)*
 * line in api-endpoints-plan, grouped by its route section.
 */
export enum AuditAction {
  // api-endpoints-plan §1.1
  DEVICE_REGISTERED = 'DEVICE_REGISTERED',

  // api-endpoints-plan §1.2
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_LOGOUT_ALL = 'USER_LOGOUT_ALL',
  REFRESH_TOKEN_REPLAY_DETECTED = 'REFRESH_TOKEN_REPLAY_DETECTED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  EMAIL_CHANGED = 'EMAIL_CHANGED',
  EMAIL_CHANGE_REVERTED = 'EMAIL_CHANGE_REVERTED',
  DEVICE_CLAIMED = 'DEVICE_CLAIMED',

  // api-endpoints-plan §1.3
  USER_ERASED = 'USER_ERASED',

  // api-endpoints-plan §1.4, §1.5
  OWNER_REGISTRATION_SUBMITTED = 'OWNER_REGISTRATION_SUBMITTED',
  OWNER_REGISTRATION_WITHDRAWN = 'OWNER_REGISTRATION_WITHDRAWN',
  OWNER_REGISTRATION_APPROVED = 'OWNER_REGISTRATION_APPROVED',
  OWNER_REGISTRATION_REJECTED = 'OWNER_REGISTRATION_REJECTED',
  OWNER_NATIONAL_ID_REVEALED = 'OWNER_NATIONAL_ID_REVEALED',
  OWNER_PII_REDACTED = 'OWNER_PII_REDACTED',

  // api-endpoints-plan §1.6
  STAFF_USER_CREATED = 'STAFF_USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_ROLES_UPDATED = 'USER_ROLES_UPDATED',
  USER_LOCKED = 'USER_LOCKED',
  USER_UNLOCKED = 'USER_UNLOCKED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_RESTORED = 'USER_RESTORED',
  USER_SESSIONS_REVOKED = 'USER_SESSIONS_REVOKED',
  ROLE_CREATED = 'ROLE_CREATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_PERMISSIONS_UPDATED = 'ROLE_PERMISSIONS_UPDATED',
  ROLE_DELETED = 'ROLE_DELETED',

  // api-endpoints-plan §1.10
  ACCOUNT_RECOVERY_OPENED = 'ACCOUNT_RECOVERY_OPENED',
  ACCOUNT_RECOVERY_APPROVED = 'ACCOUNT_RECOVERY_APPROVED',
  ACCOUNT_RECOVERY_REJECTED = 'ACCOUNT_RECOVERY_REJECTED',
  ACCOUNT_RECOVERY_CANCELLED_BY_OWNER = 'ACCOUNT_RECOVERY_CANCELLED_BY_OWNER',
  ACCOUNT_RECOVERY_COMPLETED = 'ACCOUNT_RECOVERY_COMPLETED',
  ACCOUNT_RECOVERY_EXPIRED = 'ACCOUNT_RECOVERY_EXPIRED',

  // api-endpoints-plan §3.3, §3.4
  SUBMISSION_CREATED = 'SUBMISSION_CREATED',
  SUBMISSION_SUPERSEDED = 'SUBMISSION_SUPERSEDED',
  SUBMISSION_WITHDRAWN = 'SUBMISSION_WITHDRAWN',
  SUBMISSION_APPROVED = 'SUBMISSION_APPROVED',
  SUBMISSION_REJECTED = 'SUBMISSION_REJECTED',

  // api-endpoints-plan §3.3, §3.5
  PLACE_DEACTIVATED_BY_OWNER = 'PLACE_DEACTIVATED_BY_OWNER',
  PLACE_REACTIVATED = 'PLACE_REACTIVATED',
  PLACE_CREATED = 'PLACE_CREATED',
  PLACE_EDITED = 'PLACE_EDITED',
  PLACE_EDITORIAL_UPDATED = 'PLACE_EDITORIAL_UPDATED',
  PLACE_PHOTOS_REPLACED = 'PLACE_PHOTOS_REPLACED',
  PLACE_MENU_REPLACED = 'PLACE_MENU_REPLACED',
  PLACE_HOURS_REPLACED = 'PLACE_HOURS_REPLACED',
  PLACE_ACTIVATION_REQUESTED = 'PLACE_ACTIVATION_REQUESTED',
  PLACE_ACTIVATED = 'PLACE_ACTIVATED',
  PLACE_DEACTIVATED = 'PLACE_DEACTIVATED',
  PLACE_DELETED = 'PLACE_DELETED',
  PLACE_RESTORED = 'PLACE_RESTORED',

  // api-endpoints-plan §3.6
  TOUR_CREATED = 'TOUR_CREATED',
  TOUR_UPDATED = 'TOUR_UPDATED',
  TOUR_STOPS_REPLACED = 'TOUR_STOPS_REPLACED',
  TOUR_ACTIVATED = 'TOUR_ACTIVATED',
  TOUR_DEACTIVATED = 'TOUR_DEACTIVATED',
  TOUR_DELETED = 'TOUR_DELETED',
  TOUR_RESTORED = 'TOUR_RESTORED',
  CATEGORY_CREATED = 'CATEGORY_CREATED',
  CATEGORY_UPDATED = 'CATEGORY_UPDATED',
  AREA_CREATED = 'AREA_CREATED',
  AREA_UPDATED = 'AREA_UPDATED',
  MAP_PACK_REGISTERED = 'MAP_PACK_REGISTERED',
  MAP_PACK_PUBLISHED = 'MAP_PACK_PUBLISHED',

  // api-endpoints-plan §4.3–§4.5
  SYNTHESIS_JOB_CREATED = 'SYNTHESIS_JOB_CREATED',
  SYNTHESIS_JOB_PAUSED = 'SYNTHESIS_JOB_PAUSED',
  SYNTHESIS_JOB_RESUMED = 'SYNTHESIS_JOB_RESUMED',
  SYNTHESIS_JOB_CANCELLED = 'SYNTHESIS_JOB_CANCELLED',
  SYNTHESIS_JOB_RETRIED = 'SYNTHESIS_JOB_RETRIED',
  PRONUNCIATION_CREATED = 'PRONUNCIATION_CREATED',
  PRONUNCIATION_UPDATED = 'PRONUNCIATION_UPDATED',
  PRONUNCIATION_DELETED = 'PRONUNCIATION_DELETED',
  LOCALIZATION_EDITED = 'LOCALIZATION_EDITED',
  LOCALIZATION_REVERTED = 'LOCALIZATION_REVERTED',

  // api-endpoints-plan §5, §6.2, §6.3
  BILLING_CHECKOUT_STARTED = 'BILLING_CHECKOUT_STARTED',
  BILLING_PORTAL_OPENED = 'BILLING_PORTAL_OPENED',
  BOOSTS_UPDATED = 'BOOSTS_UPDATED',
  PAYOUT_ACCOUNT_CREATED = 'PAYOUT_ACCOUNT_CREATED',
  ENTITLEMENTS_OVERRIDDEN = 'ENTITLEMENTS_OVERRIDDEN',
  ENTITLEMENTS_UNPINNED = 'ENTITLEMENTS_UNPINNED',
  BILLING_SUBSCRIPTION_CHANGED = 'BILLING_SUBSCRIPTION_CHANGED',
  BILLING_ENTITLEMENTS_APPLIED = 'BILLING_ENTITLEMENTS_APPLIED',
  VOUCHER_OFFER_CREATED = 'VOUCHER_OFFER_CREATED',
  VOUCHER_OFFER_UPDATED = 'VOUCHER_OFFER_UPDATED',
  VOUCHER_OFFER_SUBMITTED = 'VOUCHER_OFFER_SUBMITTED',
  VOUCHER_OFFER_PAUSED = 'VOUCHER_OFFER_PAUSED',
  VOUCHER_OFFER_ARCHIVED = 'VOUCHER_OFFER_ARCHIVED',
  VOUCHER_OFFER_APPROVED = 'VOUCHER_OFFER_APPROVED',
  VOUCHER_OFFER_REJECTED = 'VOUCHER_OFFER_REJECTED',
  VOUCHER_REDEEMED = 'VOUCHER_REDEEMED',
  VOUCHER_REISSUED = 'VOUCHER_REISSUED',
  STAFF_INVITED = 'STAFF_INVITED',
  STAFF_INVITATION_ACCEPTED = 'STAFF_INVITATION_ACCEPTED',
  STAFF_SCOPE_UPDATED = 'STAFF_SCOPE_UPDATED',
  STAFF_REVOKED = 'STAFF_REVOKED',

  // api-endpoints-plan §6.1–§6.3
  PLAN_CREATED = 'PLAN_CREATED',
  PLAN_UPDATED = 'PLAN_UPDATED',
  PLAN_PRICE_REGISTERED = 'PLAN_PRICE_REGISTERED',
  PLAN_APPLIED = 'PLAN_APPLIED',
  PLAN_RETIRED = 'PLAN_RETIRED',
  REFUND_CREATED = 'REFUND_CREATED',
  ORDER_PAID = 'ORDER_PAID',
  ORDER_REFUNDED = 'ORDER_REFUNDED',
  DISPUTE_OPENED = 'DISPUTE_OPENED',
  BILLING_EVENT_REPLAYED = 'BILLING_EVENT_REPLAYED',
  BILLING_WEBHOOK_FAILED = 'BILLING_WEBHOOK_FAILED',
}

/** Every `AuditAction` value. */
export const AUDIT_ACTIONS = Object.values(AuditAction);

/** Resource kinds an audit row can point at (rdm-spec I-11 `resource_type`). */
export enum AuditResourceType {
  USER = 'USER',
  DEVICE = 'DEVICE',
  ROLE = 'ROLE',
  OWNER_REGISTRATION = 'OWNER_REGISTRATION',
  PLACE = 'PLACE',
  SUBMISSION = 'SUBMISSION',
  TOUR = 'TOUR',
  CATEGORY = 'CATEGORY',
  AREA = 'AREA',
  PRONUNCIATION = 'PRONUNCIATION',
  SYNTHESIS_JOB = 'SYNTHESIS_JOB',
  PLAN = 'PLAN',
  BILLING_ACCOUNT = 'BILLING_ACCOUNT',
  BILLING_EVENT = 'BILLING_EVENT',
  VOUCHER_OFFER = 'VOUCHER_OFFER',
  ORDER = 'ORDER',
  VOUCHER = 'VOUCHER',
  MAP_PACK = 'MAP_PACK',
  LOCALIZATION = 'LOCALIZATION',
  STAFF_MEMBERSHIP = 'STAFF_MEMBERSHIP',
  ACCOUNT_RECOVERY = 'ACCOUNT_RECOVERY',
}

/** Every `AuditResourceType` value. */
export const AUDIT_RESOURCE_TYPES = Object.values(AuditResourceType);

/** Who performed an audited action (rdm-spec I-11 `actor_type`). */
export enum AuditActorType {
  USER = 'USER',
  DEVICE = 'DEVICE',
  SYSTEM = 'SYSTEM',
  STRIPE = 'STRIPE',
  /** A caller with no account and no device — a failed console login for an unknown email. */
  ANONYMOUS = 'ANONYMOUS',
}

/** Every `AuditActorType` value. */
export const AUDIT_ACTOR_TYPES = Object.values(AuditActorType);

/**
 * The resource type each action points at (rdm-spec I-11). The audit event schema refuses any
 * other. A `LOCALIZATION` row's `resource.id` is the correction's id (rdm-spec N-7): a
 * localization itself is keyed by target and language, not by a uuid.
 */
export const AUDIT_ACTION_RESOURCE: Readonly<Record<AuditAction, AuditResourceType>> = {
  [AuditAction.DEVICE_REGISTERED]: AuditResourceType.DEVICE,
  [AuditAction.USER_REGISTERED]: AuditResourceType.USER,
  [AuditAction.USER_LOGIN]: AuditResourceType.USER,
  [AuditAction.USER_LOGIN_FAILED]: AuditResourceType.USER,
  [AuditAction.USER_LOGOUT]: AuditResourceType.USER,
  [AuditAction.USER_LOGOUT_ALL]: AuditResourceType.USER,
  [AuditAction.REFRESH_TOKEN_REPLAY_DETECTED]: AuditResourceType.USER,
  [AuditAction.PASSWORD_RESET_REQUESTED]: AuditResourceType.USER,
  [AuditAction.PASSWORD_RESET_COMPLETED]: AuditResourceType.USER,
  [AuditAction.PASSWORD_CHANGED]: AuditResourceType.USER,
  [AuditAction.EMAIL_VERIFIED]: AuditResourceType.USER,
  [AuditAction.EMAIL_CHANGED]: AuditResourceType.USER,
  [AuditAction.EMAIL_CHANGE_REVERTED]: AuditResourceType.USER,
  [AuditAction.DEVICE_CLAIMED]: AuditResourceType.DEVICE,
  [AuditAction.USER_ERASED]: AuditResourceType.USER,
  [AuditAction.OWNER_REGISTRATION_SUBMITTED]: AuditResourceType.OWNER_REGISTRATION,
  [AuditAction.OWNER_REGISTRATION_WITHDRAWN]: AuditResourceType.OWNER_REGISTRATION,
  [AuditAction.OWNER_REGISTRATION_APPROVED]: AuditResourceType.OWNER_REGISTRATION,
  [AuditAction.OWNER_REGISTRATION_REJECTED]: AuditResourceType.OWNER_REGISTRATION,
  [AuditAction.OWNER_NATIONAL_ID_REVEALED]: AuditResourceType.OWNER_REGISTRATION,
  [AuditAction.OWNER_PII_REDACTED]: AuditResourceType.OWNER_REGISTRATION,
  [AuditAction.STAFF_USER_CREATED]: AuditResourceType.USER,
  [AuditAction.USER_UPDATED]: AuditResourceType.USER,
  [AuditAction.USER_ROLES_UPDATED]: AuditResourceType.USER,
  [AuditAction.USER_LOCKED]: AuditResourceType.USER,
  [AuditAction.USER_UNLOCKED]: AuditResourceType.USER,
  [AuditAction.USER_DEACTIVATED]: AuditResourceType.USER,
  [AuditAction.USER_RESTORED]: AuditResourceType.USER,
  [AuditAction.USER_SESSIONS_REVOKED]: AuditResourceType.USER,
  [AuditAction.ROLE_CREATED]: AuditResourceType.ROLE,
  [AuditAction.ROLE_UPDATED]: AuditResourceType.ROLE,
  [AuditAction.ROLE_PERMISSIONS_UPDATED]: AuditResourceType.ROLE,
  [AuditAction.ROLE_DELETED]: AuditResourceType.ROLE,
  [AuditAction.ACCOUNT_RECOVERY_OPENED]: AuditResourceType.ACCOUNT_RECOVERY,
  [AuditAction.ACCOUNT_RECOVERY_APPROVED]: AuditResourceType.ACCOUNT_RECOVERY,
  [AuditAction.ACCOUNT_RECOVERY_REJECTED]: AuditResourceType.ACCOUNT_RECOVERY,
  [AuditAction.ACCOUNT_RECOVERY_CANCELLED_BY_OWNER]: AuditResourceType.ACCOUNT_RECOVERY,
  [AuditAction.ACCOUNT_RECOVERY_COMPLETED]: AuditResourceType.ACCOUNT_RECOVERY,
  [AuditAction.ACCOUNT_RECOVERY_EXPIRED]: AuditResourceType.ACCOUNT_RECOVERY,
  [AuditAction.SUBMISSION_CREATED]: AuditResourceType.SUBMISSION,
  [AuditAction.SUBMISSION_SUPERSEDED]: AuditResourceType.SUBMISSION,
  [AuditAction.SUBMISSION_WITHDRAWN]: AuditResourceType.SUBMISSION,
  [AuditAction.SUBMISSION_APPROVED]: AuditResourceType.SUBMISSION,
  [AuditAction.SUBMISSION_REJECTED]: AuditResourceType.SUBMISSION,
  [AuditAction.PLACE_DEACTIVATED_BY_OWNER]: AuditResourceType.PLACE,
  [AuditAction.PLACE_REACTIVATED]: AuditResourceType.PLACE,
  [AuditAction.PLACE_CREATED]: AuditResourceType.PLACE,
  [AuditAction.PLACE_EDITED]: AuditResourceType.PLACE,
  [AuditAction.PLACE_EDITORIAL_UPDATED]: AuditResourceType.PLACE,
  [AuditAction.PLACE_PHOTOS_REPLACED]: AuditResourceType.PLACE,
  [AuditAction.PLACE_MENU_REPLACED]: AuditResourceType.PLACE,
  [AuditAction.PLACE_HOURS_REPLACED]: AuditResourceType.PLACE,
  [AuditAction.PLACE_ACTIVATION_REQUESTED]: AuditResourceType.PLACE,
  [AuditAction.PLACE_ACTIVATED]: AuditResourceType.PLACE,
  [AuditAction.PLACE_DEACTIVATED]: AuditResourceType.PLACE,
  [AuditAction.PLACE_DELETED]: AuditResourceType.PLACE,
  [AuditAction.PLACE_RESTORED]: AuditResourceType.PLACE,
  [AuditAction.TOUR_CREATED]: AuditResourceType.TOUR,
  [AuditAction.TOUR_UPDATED]: AuditResourceType.TOUR,
  [AuditAction.TOUR_STOPS_REPLACED]: AuditResourceType.TOUR,
  [AuditAction.TOUR_ACTIVATED]: AuditResourceType.TOUR,
  [AuditAction.TOUR_DEACTIVATED]: AuditResourceType.TOUR,
  [AuditAction.TOUR_DELETED]: AuditResourceType.TOUR,
  [AuditAction.TOUR_RESTORED]: AuditResourceType.TOUR,
  [AuditAction.CATEGORY_CREATED]: AuditResourceType.CATEGORY,
  [AuditAction.CATEGORY_UPDATED]: AuditResourceType.CATEGORY,
  [AuditAction.AREA_CREATED]: AuditResourceType.AREA,
  [AuditAction.AREA_UPDATED]: AuditResourceType.AREA,
  [AuditAction.MAP_PACK_REGISTERED]: AuditResourceType.MAP_PACK,
  [AuditAction.MAP_PACK_PUBLISHED]: AuditResourceType.MAP_PACK,
  [AuditAction.SYNTHESIS_JOB_CREATED]: AuditResourceType.SYNTHESIS_JOB,
  [AuditAction.SYNTHESIS_JOB_PAUSED]: AuditResourceType.SYNTHESIS_JOB,
  [AuditAction.SYNTHESIS_JOB_RESUMED]: AuditResourceType.SYNTHESIS_JOB,
  [AuditAction.SYNTHESIS_JOB_CANCELLED]: AuditResourceType.SYNTHESIS_JOB,
  [AuditAction.SYNTHESIS_JOB_RETRIED]: AuditResourceType.SYNTHESIS_JOB,
  [AuditAction.PRONUNCIATION_CREATED]: AuditResourceType.PRONUNCIATION,
  [AuditAction.PRONUNCIATION_UPDATED]: AuditResourceType.PRONUNCIATION,
  [AuditAction.PRONUNCIATION_DELETED]: AuditResourceType.PRONUNCIATION,
  [AuditAction.LOCALIZATION_EDITED]: AuditResourceType.LOCALIZATION,
  [AuditAction.LOCALIZATION_REVERTED]: AuditResourceType.LOCALIZATION,
  [AuditAction.BILLING_CHECKOUT_STARTED]: AuditResourceType.BILLING_ACCOUNT,
  [AuditAction.BILLING_PORTAL_OPENED]: AuditResourceType.BILLING_ACCOUNT,
  [AuditAction.BOOSTS_UPDATED]: AuditResourceType.BILLING_ACCOUNT,
  [AuditAction.PAYOUT_ACCOUNT_CREATED]: AuditResourceType.BILLING_ACCOUNT,
  [AuditAction.ENTITLEMENTS_OVERRIDDEN]: AuditResourceType.BILLING_ACCOUNT,
  [AuditAction.ENTITLEMENTS_UNPINNED]: AuditResourceType.BILLING_ACCOUNT,
  [AuditAction.BILLING_SUBSCRIPTION_CHANGED]: AuditResourceType.BILLING_ACCOUNT,
  [AuditAction.BILLING_ENTITLEMENTS_APPLIED]: AuditResourceType.BILLING_ACCOUNT,
  [AuditAction.VOUCHER_OFFER_CREATED]: AuditResourceType.VOUCHER_OFFER,
  [AuditAction.VOUCHER_OFFER_UPDATED]: AuditResourceType.VOUCHER_OFFER,
  [AuditAction.VOUCHER_OFFER_SUBMITTED]: AuditResourceType.VOUCHER_OFFER,
  [AuditAction.VOUCHER_OFFER_PAUSED]: AuditResourceType.VOUCHER_OFFER,
  [AuditAction.VOUCHER_OFFER_ARCHIVED]: AuditResourceType.VOUCHER_OFFER,
  [AuditAction.VOUCHER_OFFER_APPROVED]: AuditResourceType.VOUCHER_OFFER,
  [AuditAction.VOUCHER_OFFER_REJECTED]: AuditResourceType.VOUCHER_OFFER,
  [AuditAction.VOUCHER_REDEEMED]: AuditResourceType.VOUCHER,
  [AuditAction.VOUCHER_REISSUED]: AuditResourceType.VOUCHER,
  [AuditAction.STAFF_INVITED]: AuditResourceType.STAFF_MEMBERSHIP,
  [AuditAction.STAFF_INVITATION_ACCEPTED]: AuditResourceType.STAFF_MEMBERSHIP,
  [AuditAction.STAFF_SCOPE_UPDATED]: AuditResourceType.STAFF_MEMBERSHIP,
  [AuditAction.STAFF_REVOKED]: AuditResourceType.STAFF_MEMBERSHIP,
  [AuditAction.PLAN_CREATED]: AuditResourceType.PLAN,
  [AuditAction.PLAN_UPDATED]: AuditResourceType.PLAN,
  [AuditAction.PLAN_PRICE_REGISTERED]: AuditResourceType.PLAN,
  [AuditAction.PLAN_APPLIED]: AuditResourceType.PLAN,
  [AuditAction.PLAN_RETIRED]: AuditResourceType.PLAN,
  [AuditAction.REFUND_CREATED]: AuditResourceType.ORDER,
  [AuditAction.ORDER_PAID]: AuditResourceType.ORDER,
  [AuditAction.ORDER_REFUNDED]: AuditResourceType.ORDER,
  [AuditAction.DISPUTE_OPENED]: AuditResourceType.ORDER,
  [AuditAction.BILLING_EVENT_REPLAYED]: AuditResourceType.BILLING_EVENT,
  [AuditAction.BILLING_WEBHOOK_FAILED]: AuditResourceType.BILLING_EVENT,
};

/** Actions the logger also raises as alerts (api-endpoints-plan §1.2). */
export const AUDIT_ALERT_ACTIONS: ReadonlySet<AuditAction> = new Set([
  AuditAction.REFRESH_TOKEN_REPLAY_DETECTED,
  AuditAction.EMAIL_CHANGE_REVERTED,
]);

/** Upper bound of `audit_logs.user_agent` (rdm-spec I-11). */
export const MAX_USER_AGENT_LENGTH = 512;

/** Upper bound of `audit_logs.ip` — an IPv6 address in text form (rdm-spec I-11). */
export const MAX_IP_LENGTH = 45;
