/** An in-app notification kind — rdm-spec I-10 `type`. */
export enum NotificationType {
  OWNER_REGISTRATION_APPROVED = 'OWNER_REGISTRATION_APPROVED',
  OWNER_REGISTRATION_REJECTED = 'OWNER_REGISTRATION_REJECTED',
  SUBMISSION_APPROVED = 'SUBMISSION_APPROVED',
  SUBMISSION_REJECTED = 'SUBMISSION_REJECTED',
  PLACE_ACTIVATED = 'PLACE_ACTIVATED',
  PLACE_UNPUBLISHED = 'PLACE_UNPUBLISHED',
  SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_PAYMENT_FAILED = 'SUBSCRIPTION_PAYMENT_FAILED',
  ENTITLEMENTS_REDUCED = 'ENTITLEMENTS_REDUCED',
  VOUCHER_OFFER_APPROVED = 'VOUCHER_OFFER_APPROVED',
  VOUCHER_OFFER_REJECTED = 'VOUCHER_OFFER_REJECTED',
  VOUCHER_SOLD = 'VOUCHER_SOLD',
  VOUCHER_CODE_GUESSING_SUSPECTED = 'VOUCHER_CODE_GUESSING_SUSPECTED',
  PAYOUT_ACCOUNT_ACTION_REQUIRED = 'PAYOUT_ACCOUNT_ACTION_REQUIRED',
  ACCOUNT_RECOVERY_PENDING = 'ACCOUNT_RECOVERY_PENDING',
  ACCOUNT_RECOVERY_COMPLETED = 'ACCOUNT_RECOVERY_COMPLETED',
  PLACE_EDITED_BY_ADMIN = 'PLACE_EDITED_BY_ADMIN',
  PLACE_NARRATION_FAILED = 'PLACE_NARRATION_FAILED',
}

/** Every `NotificationType` value. */
export const NOTIFICATION_TYPES = Object.values(NotificationType);

/** A transactional email — rdm-spec I-13 `template`. */
export enum EmailTemplate {
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  ACCOUNT_SETUP = 'ACCOUNT_SETUP',
  EMAIL_CHANGE = 'EMAIL_CHANGE',
  EMAIL_CHANGED_NOTICE = 'EMAIL_CHANGED_NOTICE',
  STAFF_INVITE = 'STAFF_INVITE',
  OWNER_REGISTRATION_OUTCOME = 'OWNER_REGISTRATION_OUTCOME',
  SUBMISSION_OUTCOME = 'SUBMISSION_OUTCOME',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  ENTITLEMENTS_REDUCED = 'ENTITLEMENTS_REDUCED',
  ACCOUNT_RECOVERY_NOTICE = 'ACCOUNT_RECOVERY_NOTICE',
  VOUCHER_MOVED = 'VOUCHER_MOVED',
  VOUCHER_REFUNDED = 'VOUCHER_REFUNDED',
}

/** Every `EmailTemplate` value. */
export const EMAIL_TEMPLATES = Object.values(EmailTemplate);

/** Which provider sent an email — rdm-spec I-13 `provider`. */
export enum EmailProvider {
  RESEND = 'RESEND',
  NODEMAILER = 'NODEMAILER',
}

/** Every `EmailProvider` value. */
export const EMAIL_PROVIDERS = Object.values(EmailProvider);

/** An email's delivery state — rdm-spec I-13 `status`. */
export enum EmailDeliveryStatus {
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  BOUNCED = 'BOUNCED',
  COMPLAINED = 'COMPLAINED',
  FAILED = 'FAILED',
}

/** Every `EmailDeliveryStatus` value. */
export const EMAIL_DELIVERY_STATUSES = Object.values(EmailDeliveryStatus);

/** How an email bounced — rdm-spec I-13 `bounce_type`. */
export enum EmailBounceType {
  HARD = 'HARD',
  SOFT = 'SOFT',
}

/** Every `EmailBounceType` value. */
export const EMAIL_BOUNCE_TYPES = Object.values(EmailBounceType);
